name: Django compression middleware

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: ["2.7", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", pypy-2.7, pypy-3.6, pypy-3.7, pypy-3.8, pypy-3.9]


    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
